apiVersion: v2
name: viseron
description: A Helm chart for viseron
type: application
version: 1.0.0
appVersion: "3.0.0"  # default viseron image tag
maintainers:
  - name: carlosrodfern
  - name: roflcoopter
