apiVersion: v2
name: viseron
description: A Helm chart for viseron
type: application
version: 1.0.3
appVersion: "3.2.1"  # default viseron image tag
maintainers:
  - name: carlosrodfern
  - name: roflcoopter
