apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "viseron.fullname" . }}
  labels:
    {{- include "viseron.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "viseron.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "viseron.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "viseron.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: viseron-segments
              mountPath: /segments
            - name: viseron-snapshots
              mountPath: /snapshots
            - name: viseron-thumbnails
              mountPath: /thumbnails
            - name: viseron-eventclips
              mountPath: /event_clips
            - name: etc-localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: viseron-config
              mountPath: /config
            - name: viseron-shm
              mountPath: /dev/shm              
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: viseron-segments
          persistentVolumeClaim:
            claimName: {{ include "viseron.fullname" . }}-segments
        - name: viseron-snapshots
          persistentVolumeClaim:
            claimName: {{ include "viseron.fullname" . }}-snapshots
        - name: viseron-thumbnails
          persistentVolumeClaim:
            claimName: {{ include "viseron.fullname" . }}-thumbnails
        - name: viseron-eventclips
          persistentVolumeClaim:
            claimName: {{ include "viseron.fullname" . }}-eventclips
        - name: viseron-config
          persistentVolumeClaim:
            claimName: {{ include "viseron.fullname" . }}-config
        - name: viseron-shm
          emptyDir:
            medium: Memory
            sizeLimit: {{.Values.shm.size}}
        - name: etc-localtime
          hostPath:
            path: /etc/localtime
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
